postgres:
  adapter: postgresql
  database: activerecord_comments_test
  host: 127.0.0.1
  username: postgres
  password: postgres

mysql:
  adapter: mysql2
  database: activerecord_comments_test
  user: root
  password: password

sqlite:
  adapter: sqlite3
  database: test/db/activerecord_comments_test
  pool: 5
  timeout: 5000